export const systemV1ActionPermissions = Object.freeze([
  "system.v1_field_evidence_intake.apply",
  "system.v1_field_evidence.validate",
  "system.v1_production_env.precheck",
  "system.v1_production_env_setup.run",
  "system.v1_production_env_intake.precheck",
  "system.v1_production_env_file_audit.precheck",
  "system.v1_production_env_file_preview.precheck",
  "system.v1_production_go_live.precheck",
  "system.v1_production_persistence_evidence.run",
  "system.v1_production_first_stage_execution.run",
  "system.v1_production_first_stage_values_dry_run.precheck",
  "system.v1_production_first_stage_values_apply.run",
  "system.v1_persistence.precheck",
  "system.v1_attachment_retention.precheck",
  "system.v1_driver_readiness.precheck",
  "system.v1_runtime_readiness.precheck",
  "system.v1_v2_boundary.precheck",
  "system.v1_v2_scope_brief.refresh",
  "system.v1_release_candidate.refresh_precheck",
  "system.v1_release_candidate.refresh",
]);

const definitions = {
  office: {
    displayName: "办公室",
    department: "office",
    buttonPermissions: [
      "order.create",
      "order.confirm",
      "order.save_draft",
      "order.open_pool",
      "order.void",
      "order.quantity.adjust",
      "inventory.correction.create",
      "production.schedule.publish",
      "production.schedule.sequence.update",
      "production.report.complete",
      "packing.complete",
      "fulfillment.print",
      "fulfillment.dispatch.update",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "delivery.evidence.review",
      "fulfillment.cancel",
      "raw_material.inbound.review",
      "raw_material.label.print",
      "raw_material.exception.create",
      "statement.preview",
      "statement.send",
      "payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "todo.handle",
    ],
    actionPermissions: [
      "order.draft.recognize",
      "order.draft.save",
      "order.confirm",
      "order.void",
      "order.quantity.adjust",
      "inventory.reservation.create",
      "inventory.reservation.release",
      "inventory.correction.create",
      "production.schedule.publish",
      "production.schedule.sequence.update",
      "production.report.complete",
      "packing.complete",
      "fulfillment.exception.create",
      "fulfillment.print",
      "print.device_qa.record",
      "fulfillment.dispatch.update",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "delivery.evidence.review",
      "fulfillment.cancel",
      "raw_material.inbound.review",
      "raw_material.label.print",
      "raw_material.exception.create",
      "statement.preview",
      "statement.send",
      "statement.payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "attachment.create",
      "attachment.view",
      "master_data.import.plan.create",
      "todo.handle",
    ],
  },
  warehouse: {
    displayName: "库房 / 出库",
    department: "warehouse",
    buttonPermissions: [
      "inventory.lookup",
      "inventory.correction.create",
      "packing.complete",
      "fulfillment.print",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "raw_material.label.print",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
      "fulfillment.exception.create",
      "todo.handle",
    ],
    actionPermissions: [
      "inventory.correction.create",
      "attachment.inventory_correction.create",
      "inventory.reservation.release",
      "packing.complete",
      "fulfillment.exception.create",
      "fulfillment.print",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "raw_material.label.print",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
      "todo.handle",
    ],
  },
  finance: {
    displayName: "财务 / 对账",
    department: "finance",
    buttonPermissions: [
      "statement.preview",
      "statement.send",
      "payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "raw_material.supplier_payable.create",
      "raw_material.supplier_payment.confirm",
      "raw_material.cost.view",
      "raw_material.cost.allocate",
      "raw_material.cost.confirm",
      "raw_material.cost.calibrate",
      "raw_material.margin.snapshot",
      "raw_material.margin.review",
      "todo.handle",
    ],
    actionPermissions: [
      "statement.preview",
      "statement.send",
      "statement.payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "raw_material.supplier_payable.create",
      "raw_material.supplier_payment.confirm",
      "raw_material.cost.view",
      "raw_material.cost.allocate",
      "raw_material.cost.confirm",
      "raw_material.cost.calibrate",
      "raw_material.margin.snapshot",
      "raw_material.margin.review",
      "attachment.create",
      "attachment.view",
      "todo.handle",
    ],
  },
  management: {
    displayName: "管理",
    department: "management",
    buttonPermissions: [
      "order.create",
      "order.confirm",
      "order.save_draft",
      "order.open_pool",
      "order.void",
      "order.quantity.adjust",
      "inventory.lookup",
      "inventory.correction.create",
      "inventory.correction.confirm",
      "production.schedule.publish",
      "production.schedule.sequence.update",
      "production.report.complete",
      "packing.complete",
      "fulfillment.print",
      "fulfillment.dispatch.update",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "delivery.evidence.review",
      "fulfillment.cancel",
      "raw_material.inbound.review",
      "raw_material.label.print",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
      "raw_material.exception.create",
      "raw_material.cost.view",
      "raw_material.cost.allocate",
      "raw_material.cost.confirm",
      "raw_material.cost.calibrate",
      "raw_material.margin.snapshot",
      "raw_material.margin.review",
      "raw_material.supplier_payable.create",
      "raw_material.supplier_payment.confirm",
      "statement.preview",
      "statement.send",
      "payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "todo.handle",
      "permission.manage",
    ],
    actionPermissions: [
      "order.draft.recognize",
      "order.draft.save",
      "order.confirm",
      "order.void",
      "order.quantity.adjust",
      "inventory.reservation.create",
      "inventory.reservation.release",
      "inventory.correction.confirm",
      "production.schedule.publish",
      "production.schedule.sequence.update",
      "production.report.complete",
      "packing.complete",
      "fulfillment.exception.create",
      "fulfillment.print",
      "print.device_qa.record",
      "fulfillment.dispatch.update",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "delivery.evidence.review",
      "fulfillment.cancel",
      "raw_material.inbound.review",
      "raw_material.label.print",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
      "raw_material.exception.create",
      "raw_material.cost.view",
      "raw_material.cost.allocate",
      "raw_material.cost.confirm",
      "raw_material.cost.calibrate",
      "raw_material.margin.snapshot",
      "raw_material.margin.review",
      "raw_material.supplier_payable.create",
      "raw_material.supplier_payment.confirm",
      "statement.preview",
      "statement.send",
      "statement.payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "attachment.create",
      "attachment.view",
      "master_data.import.plan.create",
      "master_data.import.execute",
      "master_data.employee_account.review",
      "master_data.employee_account.password.issue",
      ...systemV1ActionPermissions,
      "todo.handle",
      "permission.manage",
    ],
  },
  technical_operations: {
    displayName: "技术运维",
    department: "system",
    buttonPermissions: ["permission.manage"],
    actionPermissions: [...systemV1ActionPermissions, "permission.manage"],
  },
  driver: {
    displayName: "司机",
    department: "delivery",
    buttonPermissions: [
      "delivery.view",
      "delivery.load_confirm",
      "delivery.complete",
      "delivery.exception.create",
      "delivery.device_qa.record",
    ],
    actionPermissions: [
      "delivery.view",
      "delivery.load_confirm",
      "delivery.complete",
      "delivery.exception.create",
      "delivery.device_qa.record",
      "attachment.delivery_evidence.create",
    ],
  },
  workshop: {
    displayName: "车间报工",
    department: "workshop",
    buttonPermissions: ["production.report.complete"],
    actionPermissions: ["production.report.complete", "attachment.finished_goods_photo.create"],
  },
  packing: {
    displayName: "打包",
    department: "packing",
    buttonPermissions: [
      "packing.complete",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
    ],
    actionPermissions: [
      "packing.complete",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
    ],
  },
  print_driver_service: {
    displayName: "打印驱动服务账号",
    department: "system",
    buttonPermissions: [],
    actionPermissions: ["print.job.callback"],
  },
};

export const roleCatalog = Object.freeze(
  Object.fromEntries(
    Object.entries(definitions).map(([roleKey, definition]) => [
      roleKey,
      Object.freeze({
        ...definition,
        buttonPermissions: Object.freeze([...definition.buttonPermissions]),
        actionPermissions: Object.freeze([...definition.actionPermissions]),
      }),
    ]),
  ),
);

export function normalizeRoleKeys(roles = []) {
  return unique(roles).filter((roleKey) => Boolean(roleCatalog[roleKey]));
}

export function getRolePermissionSet(roles = []) {
  const roleKeys = normalizeRoleKeys(roles);
  return {
    roles: roleKeys,
    buttonPermissions: unique(roleKeys.flatMap((roleKey) => roleCatalog[roleKey].buttonPermissions)),
    actionPermissions: unique(roleKeys.flatMap((roleKey) => roleCatalog[roleKey].actionPermissions)),
  };
}

export function createDisabledPermissionContext(userId = "UNAUTHENTICATED") {
  const normalizedUserId = String(userId || "UNAUTHENTICATED").trim() || "UNAUTHENTICATED";
  return {
    user: {
      userId: normalizedUserId,
      displayName: "未登录",
      defaultRole: "disabled",
      department: "unknown",
      enabled: false,
    },
    roles: [],
    grants: [],
    buttonPermissions: [],
    actionPermissions: [],
  };
}

function unique(values) {
  return [...new Set(values.filter(Boolean))];
}
