export const systemV1ActionPermissions = Object.freeze([
  "system.v1_field_evidence_intake.apply",
  "system.v1_field_evidence.validate",
  "system.v1_production_env.precheck",
  "system.v1_production_env_setup.run",
  "system.v1_production_env_intake.precheck",
  "system.v1_production_env_file_audit.precheck",
  "system.v1_production_env_file_preview.precheck",
  "system.v1_production_go_live.precheck",
  "system.v1_production_persistence_evidence.run",
  "system.v1_production_first_stage_execution.run",
  "system.v1_production_first_stage_values_dry_run.precheck",
  "system.v1_production_first_stage_values_apply.run",
  "system.v1_persistence.precheck",
  "system.v1_attachment_retention.precheck",
  "system.v1_driver_readiness.precheck",
  "system.v1_runtime_readiness.precheck",
  "system.v1_v2_boundary.precheck",
  "system.v1_v2_scope_brief.refresh",
  "system.v1_release_candidate.refresh_precheck",
  "system.v1_release_candidate.refresh",
]);

const definitions = {
  office: {
    displayName: "办公室",
    department: "office",
    buttonPermissions: [
      "order.create",
      "order.confirm",
      "order.save_draft",
      "order.open_pool",
      "order.void",
      "order.quantity.adjust",
      "inventory.correction.create",
      "production.schedule.publish",
      "production.schedule.sequence.update",
      "production.report.complete",
      "production.exception.resolve",
      "packing.complete",
      "fulfillment.print",
      "fulfillment.dispatch.update",
      "fulfillment.paper.handoff",
      "fulfillment.warehouse.execute",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "delivery.evidence.review",
      "fulfillment.cancel",
      "raw_material.inbound.review",
      "master_data.raw_material_color.manage",
      "raw_material.label.print",
      "raw_material.label.attach_confirm",
      "raw_material.exception.create",
      "maintenance.task.read",
      "maintenance.task.create",
      "statement.preview",
      "statement.send",
      "payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "business_decision.read",
      "business_decision.record_delegated",
      "production.schedule.record_delegated",
      "raw_material.purchase.record_delegated",
      "fulfillment.quantity_variance.record_delegated",
      "statement.variance.record_delegated",
      "statement.write_off.record_delegated",
      "todo.handle",
      "attendance.self.read",
    ],
    actionPermissions: [
      "order.draft.recognize",
      "order.draft.save",
      "order.confirm",
      "order.void",
      "order.quantity.adjust",
      "inventory.reservation.create",
      "inventory.reservation.release",
      "inventory.correction.create",
      "production.schedule.publish",
      "production.schedule.sequence.update",
      "production.report.complete",
      "production.exception.resolve",
      "packing.complete",
      "fulfillment.exception.create",
      "fulfillment.quantity_variance.resolve",
      "fulfillment.print",
      "print.device_qa.record",
      "fulfillment.dispatch.update",
      "fulfillment.paper.handoff",
      "fulfillment.warehouse.execute",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "delivery.evidence.review",
      "fulfillment.cancel",
      "raw_material.inbound.review",
      "master_data.raw_material_color.manage",
      "raw_material.label.print",
      "raw_material.label.attach_confirm",
      "raw_material.exception.create",
      "maintenance.task.read",
      "maintenance.task.create",
      "statement.preview",
      "statement.send",
      "statement.payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "business_decision.read",
      "business_decision.record_delegated",
      "order.priority.record_delegated",
      "production.schedule.record_delegated",
      "raw_material.purchase.record_delegated",
      "fulfillment.quantity_variance.record_delegated",
      "statement.variance.record_delegated",
      "statement.write_off.record_delegated",
      "attachment.create",
      "attachment.view",
      "master_data.import.plan.create",
      "todo.handle",
      "attendance.self.read",
    ],
  },
  warehouse: {
    displayName: "库房 / 出库",
    department: "warehouse",
    buttonPermissions: [
      "inventory.lookup",
      "inventory.correction.create",
      "packing.complete",
      "fulfillment.print",
      "fulfillment.warehouse.execute",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "raw_material.label.print",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
      "fulfillment.exception.create",
      "todo.handle",
      "attendance.self.read",
    ],
    actionPermissions: [
      "inventory.correction.create",
      "attachment.inventory_correction.create",
      "inventory.reservation.release",
      "packing.complete",
      "fulfillment.exception.create",
      "fulfillment.print",
      "fulfillment.warehouse.execute",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "raw_material.label.print",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
      "todo.handle",
      "attendance.self.read",
    ],
  },
  finance: {
    displayName: "财务 / 对账",
    department: "finance",
    buttonPermissions: [
      "statement.preview",
      "statement.send",
      "payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "business_decision.read",
      "raw_material.supplier_payable.create",
      "raw_material.supplier_payment.confirm",
      "raw_material.cost.view",
      "raw_material.cost.allocate",
      "raw_material.cost.confirm",
      "raw_material.cost.calibrate",
      "raw_material.margin.snapshot",
      "raw_material.margin.review",
      "todo.handle",
      "attendance.self.read",
      "payroll.preview",
      "payroll.export",
      "payroll.review",
      "payroll.lock",
      "payroll.payment.confirm",
    ],
    actionPermissions: [
      "statement.preview",
      "statement.send",
      "statement.payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "business_decision.read",
      "raw_material.supplier_payable.create",
      "raw_material.supplier_payment.confirm",
      "raw_material.cost.view",
      "raw_material.cost.allocate",
      "raw_material.cost.confirm",
      "raw_material.cost.calibrate",
      "raw_material.margin.snapshot",
      "raw_material.margin.review",
      "attachment.create",
      "attachment.view",
      "todo.handle",
      "attendance.self.read",
      "payroll.preview",
      "payroll.export",
      "payroll.review",
      "payroll.lock",
      "payroll.payment.confirm",
    ],
  },
  management: {
    displayName: "管理",
    department: "management",
    buttonPermissions: [
      "order.create",
      "order.confirm",
      "order.save_draft",
      "order.open_pool",
      "order.void",
      "order.quantity.adjust",
      "inventory.lookup",
      "inventory.correction.create",
      "inventory.correction.confirm",
      "production.schedule.publish",
      "production.schedule.sequence.update",
      "production.report.complete",
      "production.exception.resolve",
      "packing.complete",
      "fulfillment.print",
      "fulfillment.dispatch.update",
      "fulfillment.paper.handoff",
      "fulfillment.warehouse.execute",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "delivery.evidence.review",
      "fulfillment.cancel",
      "raw_material.inbound.review",
      "master_data.raw_material_color.manage",
      "raw_material.label.print",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
      "raw_material.exception.create",
      "maintenance.task.read",
      "maintenance.task.create",
      "raw_material.cost.view",
      "raw_material.cost.allocate",
      "raw_material.cost.confirm",
      "raw_material.cost.calibrate",
      "raw_material.margin.snapshot",
      "raw_material.margin.review",
      "raw_material.supplier_payable.create",
      "raw_material.supplier_payment.confirm",
      "statement.preview",
      "statement.send",
      "payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "business_decision.read",
      "business_decision.act_directly",
      "business_decision.authorization.manage",
      "order.priority.direct",
      "production.schedule.direct",
      "raw_material.purchase.direct",
      "fulfillment.quantity_variance.direct",
      "statement.variance.direct",
      "statement.write_off.direct",
      "major_exception.direct",
      "todo.handle",
      "permission.manage",
      "attendance.self.read",
      "attendance.sync",
      "attendance.review",
      "payroll.preview",
      "payroll.export",
      "payroll.policy.manage",
      "payroll.review",
      "payroll.lock",
      "payroll.payment.confirm",
    ],
    actionPermissions: [
      "order.draft.recognize",
      "order.draft.save",
      "order.confirm",
      "order.void",
      "order.quantity.adjust",
      "inventory.reservation.create",
      "inventory.reservation.release",
      "inventory.correction.confirm",
      "production.schedule.publish",
      "production.schedule.sequence.update",
      "production.report.complete",
      "production.exception.resolve",
      "packing.complete",
      "fulfillment.exception.create",
      "fulfillment.quantity_variance.resolve",
      "fulfillment.print",
      "print.device_qa.record",
      "fulfillment.dispatch.update",
      "fulfillment.paper.handoff",
      "fulfillment.warehouse.execute",
      "fulfillment.complete",
      "fulfillment.pickup.confirm",
      "delivery.evidence.review",
      "fulfillment.cancel",
      "raw_material.inbound.review",
      "raw_material.label.print",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
      "raw_material.exception.create",
      "maintenance.task.read",
      "maintenance.task.create",
      "raw_material.cost.view",
      "raw_material.cost.allocate",
      "raw_material.cost.confirm",
      "raw_material.cost.calibrate",
      "raw_material.margin.snapshot",
      "raw_material.margin.review",
      "raw_material.supplier_payable.create",
      "raw_material.supplier_payment.confirm",
      "statement.preview",
      "statement.send",
      "statement.payment.record",
      "statement.variance.handle",
      "statement.write_off",
      "business_decision.read",
      "business_decision.act_directly",
      "business_decision.authorization.manage",
      "order.priority.direct",
      "production.schedule.direct",
      "raw_material.purchase.direct",
      "fulfillment.quantity_variance.direct",
      "statement.variance.direct",
      "statement.write_off.direct",
      "major_exception.direct",
      "attachment.create",
      "attachment.view",
      "master_data.import.plan.create",
      "master_data.import.execute",
      "master_data.employee_account.review",
      "master_data.employee_account.password.issue",
      "master_data.employee_profile.manage",
      "master_data.raw_material_color.manage",
      "attendance.self.read",
      "attendance.sync",
      "attendance.review",
      "payroll.preview",
      "payroll.export",
      "payroll.policy.manage",
      "payroll.review",
      "payroll.lock",
      "payroll.payment.confirm",
      ...systemV1ActionPermissions,
      "todo.handle",
      "permission.manage",
    ],
  },
  technical_operations: {
    displayName: "技术运维",
    department: "system",
    buttonPermissions: ["permission.manage"],
    actionPermissions: [...systemV1ActionPermissions, "attendance.self.read", "permission.manage"],
  },
  driver: {
    displayName: "司机",
    department: "delivery",
    buttonPermissions: [
      "delivery.view",
      "delivery.load_confirm",
      "delivery.complete",
      "delivery.exception.create",
      "delivery.device_qa.record",
    ],
    actionPermissions: [
      "delivery.view",
      "delivery.load_confirm",
      "delivery.complete",
      "delivery.exception.create",
      "delivery.device_qa.record",
      "attachment.delivery_evidence.create",
      "attendance.self.read",
    ],
  },
  workshop: {
    displayName: "车间报工",
    department: "workshop",
    buttonPermissions: ["production.report.complete", "raw_material.issue.create"],
    actionPermissions: ["production.report.complete", "attachment.finished_goods_photo.create", "raw_material.issue.create", "attendance.self.read"],
  },
  packing: {
    displayName: "打包",
    department: "packing",
    buttonPermissions: [
      "packing.complete",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
      "attendance.self.read",
    ],
    actionPermissions: [
      "packing.complete",
      "raw_material.label.attach_confirm",
      "raw_material.issue.create",
      "raw_material.consumption.confirm",
      "raw_material.leftover.return",
      "raw_material.leftover.review",
      "attendance.self.read",
    ],
  },
  decision_maker: {
    displayName: "经营决策",
    department: "management",
    buttonPermissions: [
      "business_decision.read",
      "business_decision.act_directly",
      "order.priority.direct",
      "production.schedule.direct",
      "raw_material.purchase.direct",
      "fulfillment.quantity_variance.direct",
      "statement.variance.direct",
      "statement.write_off.direct",
    ],
    actionPermissions: [
      "business_decision.read",
      "business_decision.act_directly",
      "order.priority.direct",
      "production.schedule.direct",
      "raw_material.purchase.direct",
      "fulfillment.quantity_variance.direct",
      "statement.variance.direct",
      "statement.write_off.direct",
      "attachment.view",
      "attendance.self.read",
    ],
  },
  decision_maker_primary: {
    displayName: "主要经营决策",
    department: "management",
    buttonPermissions: ["major_exception.direct"],
    actionPermissions: ["major_exception.direct", "attendance.self.read"],
  },
  maintenance: {
    displayName: "现场机修",
    department: "maintenance",
    buttonPermissions: ["maintenance.task.read", "maintenance.task.create", "maintenance.task.update"],
    actionPermissions: ["maintenance.task.read", "maintenance.task.create", "maintenance.task.update", "attachment.maintenance.create", "attendance.self.read"],
  },
  print_driver_service: {
    displayName: "打印驱动服务账号",
    department: "system",
    buttonPermissions: [],
    actionPermissions: ["print.job.callback"],
  },
};

export const roleCatalog = Object.freeze(
  Object.fromEntries(
    Object.entries(definitions).map(([roleKey, definition]) => [
      roleKey,
      Object.freeze({
        ...definition,
        buttonPermissions: Object.freeze([...definition.buttonPermissions]),
        actionPermissions: Object.freeze([...definition.actionPermissions]),
      }),
    ]),
  ),
);

export const v1RuntimeEmployeeRoleKeys = Object.freeze([
  "office",
  "warehouse",
  "finance",
  "workshop",
  "packing",
  "driver",
  "management",
  "technical_operations",
]);

const v1RuntimeEmployeeRoleAliases = Object.freeze({
  technical_operations: Object.freeze(["技术运维", "系统运维", "运维"]),
  management: Object.freeze(["管理", "主管", "负责人"]),
  office: Object.freeze(["办公室", "文员", "录单", "客服"]),
  finance: Object.freeze(["财务", "对账", "收款"]),
  warehouse: Object.freeze(["库房", "出库", "仓库"]),
  driver: Object.freeze(["司机", "送货"]),
  packing: Object.freeze(["打包", "杂工"]),
  workshop: Object.freeze(["车间", "制袋", "丝印", "操作工"]),
});
const v1RuntimeEmployeeRoleAliasPriority = Object.freeze([
  "technical_operations",
  "management",
  "office",
  "finance",
  "warehouse",
  "driver",
  "packing",
  "workshop",
]);

export function normalizeV1RuntimeEmployeeRoleKey(roleKey, roleName = "") {
  const normalizedKey = String(roleKey ?? "").trim();
  if (v1RuntimeEmployeeRoleKeys.includes(normalizedKey)) return normalizedKey;
  const normalizedName = String(roleName ?? "").trim();
  if (!normalizedName) return "";
  return v1RuntimeEmployeeRoleAliasPriority.find((candidate) =>
    v1RuntimeEmployeeRoleAliases[candidate].some((alias) => normalizedName.includes(alias)),
  ) ?? "";
}

export function getV1RuntimeEmployeeRoleInputLabels() {
  return v1RuntimeEmployeeRoleKeys.map((roleKey) => roleCatalog[roleKey].displayName);
}

export function splitV1RuntimeEmployeeRoleInputs(values = []) {
  const source = Array.isArray(values) ? values : [values];
  return source
    .flatMap((value) => Array.isArray(value) ? value : String(value ?? "").split(/[、,，;；|+]/u))
    .map((value) => String(value ?? "").trim())
    .filter(Boolean);
}

export function normalizeV1RuntimeEmployeeRoleKeys(values = []) {
  return unique(
    splitV1RuntimeEmployeeRoleInputs(values)
      .map((value) => normalizeV1RuntimeEmployeeRoleKey(value, value)),
  );
}

export function normalizeRoleKeys(roles = []) {
  return unique(roles).filter((roleKey) => Boolean(roleCatalog[roleKey]));
}

export function getRolePermissionSet(roles = []) {
  const roleKeys = normalizeRoleKeys(roles);
  return {
    roles: roleKeys,
    buttonPermissions: unique(roleKeys.flatMap((roleKey) => roleCatalog[roleKey].buttonPermissions)),
    actionPermissions: unique(roleKeys.flatMap((roleKey) => roleCatalog[roleKey].actionPermissions)),
  };
}

export function createDisabledPermissionContext(userId = "UNAUTHENTICATED") {
  const normalizedUserId = String(userId || "UNAUTHENTICATED").trim() || "UNAUTHENTICATED";
  return {
    user: {
      userId: normalizedUserId,
      displayName: "未登录",
      defaultRole: "disabled",
      department: "unknown",
      enabled: false,
    },
    roles: [],
    grants: [],
    buttonPermissions: [],
    actionPermissions: [],
  };
}

function unique(values) {
  return [...new Set(values.filter(Boolean))];
}
