export function normalizeRawMaterialIssueRecords(records = []) {
  return (Array.isArray(records) ? records : [])
    .map((record) => ({
      ...record,
      issueRecordId: cleanText(record.issueRecordId ?? record.id),
      inboundId: cleanText(record.inboundId),
      rollId: cleanText(record.rollId),
      sourceRollId: cleanText(record.sourceRollId),
      splitRecordId: cleanText(record.splitRecordId),
      supplierRollNo: cleanText(record.supplierRollNo),
      materialType: cleanText(record.materialType),
      productName: cleanText(record.productName),
      spec: cleanText(record.spec),
      factoryColor: cleanText(record.factoryColor),
      issuedWeightKg: Number(record.issuedWeightKg) || 0,
      issuedQuantity: Number(record.issuedQuantity) || 0,
      sourceWeightKg: Number(record.sourceWeightKg) || 0,
      remainingWeightKg: Number(record.remainingWeightKg) || 0,
      remainingMachineSideWeightKg: Number(record.remainingMachineSideWeightKg) || 0,
      unit: cleanText(record.unit),
      machineId: cleanText(record.machineId),
      productionTaskId: cleanText(record.productionTaskId),
      productionTaskMatchStatus: cleanText(record.productionTaskMatchStatus),
      productionTaskMatchReason: cleanText(record.productionTaskMatchReason),
      productionTaskOrderLineId: cleanText(record.productionTaskOrderLineId),
      productionTaskMachineId: cleanText(record.productionTaskMachineId),
      productionTaskGoodsSpec: cleanText(record.productionTaskGoodsSpec),
      issuePurpose: cleanText(record.issuePurpose) || "生产领料",
      issueMode: cleanText(record.issueMode) || "整卷/整件领料",
      consumptionStatus: cleanText(record.consumptionStatus) || "待生产消耗确认",
      issuedBy: cleanText(record.issuedBy),
      issuedByUserId: cleanText(record.issuedByUserId),
      issuedAt: cleanText(record.issuedAt),
      consumptionRecordId: cleanText(record.consumptionRecordId),
      consumedWeightKg: Number(record.consumedWeightKg) || 0,
      consumedAt: cleanText(record.consumedAt),
      consumedBy: cleanText(record.consumedBy),
      consumedByUserId: cleanText(record.consumedByUserId),
      leftoverReturnRecordId: cleanText(record.leftoverReturnRecordId),
      returnedAt: cleanText(record.returnedAt),
      returnedBy: cleanText(record.returnedBy),
      returnedByUserId: cleanText(record.returnedByUserId),
      leftoverReviewRecordId: cleanText(record.leftoverReviewRecordId),
      leftoverReviewedAt: cleanText(record.leftoverReviewedAt),
      leftoverReviewedBy: cleanText(record.leftoverReviewedBy),
      leftoverReviewedByUserId: cleanText(record.leftoverReviewedByUserId),
      costAllocationStatus: cleanText(record.costAllocationStatus),
      costAllocationDraftId: cleanText(record.costAllocationDraftId),
      allocatedCostAmount: Number(record.allocatedCostAmount) || 0,
      allocatedWeightKg: Number(record.allocatedWeightKg) || 0,
      allocatedQuantity: Number(record.allocatedQuantity) || 0,
      costConfirmationId: cleanText(record.costConfirmationId),
      confirmedCostAmount: Number(record.confirmedCostAmount) || 0,
      costConfirmedAt: cleanText(record.costConfirmedAt),
      costConfirmedBy: cleanText(record.costConfirmedBy),
      costConfirmedByUserId: cleanText(record.costConfirmedByUserId),
      lossCalibrationId: cleanText(record.lossCalibrationId),
      lossRatePercent: Number(record.lossRatePercent) || 0,
      lossCalibratedAt: cleanText(record.lossCalibratedAt),
      lossCalibratedBy: cleanText(record.lossCalibratedBy),
      lossCalibratedByUserId: cleanText(record.lossCalibratedByUserId),
      marginSnapshotId: cleanText(record.marginSnapshotId),
      marginSnapshotGeneratedAt: cleanText(record.marginSnapshotGeneratedAt),
      marginSnapshotGeneratedBy: cleanText(record.marginSnapshotGeneratedBy),
      marginSnapshotGeneratedByUserId: cleanText(record.marginSnapshotGeneratedByUserId),
      marginReportId: cleanText(record.marginReportId),
      marginReviewedAt: cleanText(record.marginReviewedAt),
      marginReviewedBy: cleanText(record.marginReviewedBy),
      marginReviewedByUserId: cleanText(record.marginReviewedByUserId),
      note: cleanText(record.note),
    }))
    .filter((record) => record.issueRecordId && record.rollId);
}

export function normalizeRawMaterialConsumptionRecords(records = []) {
  return (Array.isArray(records) ? records : [])
    .map((record) => ({
      ...record,
      consumptionRecordId: cleanText(record.consumptionRecordId ?? record.id),
      inboundId: cleanText(record.inboundId),
      issueRecordId: cleanText(record.issueRecordId),
      rollId: cleanText(record.rollId),
      supplierRollNo: cleanText(record.supplierRollNo),
      materialType: cleanText(record.materialType),
      productName: cleanText(record.productName),
      spec: cleanText(record.spec),
      factoryColor: cleanText(record.factoryColor),
      consumedWeightKg: Number(record.consumedWeightKg) || 0,
      consumedQuantity: Number(record.consumedQuantity) || 0,
      consumedFromWeightKg: Number(record.consumedFromWeightKg) || 0,
      remainingMachineSideWeightKg: Number(record.remainingMachineSideWeightKg) || 0,
      partialConsumption: Boolean(record.partialConsumption),
      unit: cleanText(record.unit),
      machineId: cleanText(record.machineId),
      productionTaskId: cleanText(record.productionTaskId),
      machineCount: cleanText(record.machineCount),
      qualifiedOutputQuantity: Number(record.qualifiedOutputQuantity) || 0,
      consumptionStatus: cleanText(record.consumptionStatus) || "已确认消耗",
      confirmedBy: cleanText(record.confirmedBy),
      confirmedByUserId: cleanText(record.confirmedByUserId),
      confirmedAt: cleanText(record.confirmedAt),
      costAllocationStatus: cleanText(record.costAllocationStatus),
      costAllocationDraftId: cleanText(record.costAllocationDraftId),
      allocatedCostAmount: Number(record.allocatedCostAmount) || 0,
      allocatedWeightKg: Number(record.allocatedWeightKg) || 0,
      allocatedQuantity: Number(record.allocatedQuantity) || 0,
      costConfirmationId: cleanText(record.costConfirmationId),
      confirmedCostAmount: Number(record.confirmedCostAmount) || 0,
      costConfirmedAt: cleanText(record.costConfirmedAt),
      costConfirmedBy: cleanText(record.costConfirmedBy),
      costConfirmedByUserId: cleanText(record.costConfirmedByUserId),
      lossCalibrationId: cleanText(record.lossCalibrationId),
      lossRatePercent: Number(record.lossRatePercent) || 0,
      lossCalibratedAt: cleanText(record.lossCalibratedAt),
      lossCalibratedBy: cleanText(record.lossCalibratedBy),
      lossCalibratedByUserId: cleanText(record.lossCalibratedByUserId),
      marginSnapshotId: cleanText(record.marginSnapshotId),
      marginSnapshotGeneratedAt: cleanText(record.marginSnapshotGeneratedAt),
      marginSnapshotGeneratedBy: cleanText(record.marginSnapshotGeneratedBy),
      marginSnapshotGeneratedByUserId: cleanText(record.marginSnapshotGeneratedByUserId),
      marginReportId: cleanText(record.marginReportId),
      marginReviewedAt: cleanText(record.marginReviewedAt),
      marginReviewedBy: cleanText(record.marginReviewedBy),
      marginReviewedByUserId: cleanText(record.marginReviewedByUserId),
      note: cleanText(record.note),
    }))
    .filter((record) => record.consumptionRecordId && record.rollId);
}

export function normalizeRawMaterialLeftoverReturnRecords(records = []) {
  return (Array.isArray(records) ? records : [])
    .map((record) => ({
      ...record,
      leftoverReturnRecordId: cleanText(record.leftoverReturnRecordId ?? record.id),
      inboundId: cleanText(record.inboundId),
      issueRecordId: cleanText(record.issueRecordId),
      rollId: cleanText(record.rollId),
      supplierRollNo: cleanText(record.supplierRollNo),
      materialType: cleanText(record.materialType),
      productName: cleanText(record.productName),
      spec: cleanText(record.spec),
      factoryColor: cleanText(record.factoryColor),
      issuedWeightKg: Number(record.issuedWeightKg) || 0,
      machineSideWeightKg: Number(record.machineSideWeightKg) || 0,
      leftoverWeightKg: Number(record.leftoverWeightKg) || 0,
      leftoverQuantity: Number(record.leftoverQuantity) || 0,
      unit: cleanText(record.unit),
      machineId: cleanText(record.machineId),
      productionTaskId: cleanText(record.productionTaskId),
      returnLocation: cleanText(record.returnLocation) || "余料区",
      returnReason: cleanText(record.returnReason) || "机边余料退回",
      consumptionStatus: cleanText(record.consumptionStatus) || "已退回余料/待复核",
      returnedBy: cleanText(record.returnedBy),
      returnedByUserId: cleanText(record.returnedByUserId),
      returnedAt: cleanText(record.returnedAt),
      leftoverReviewRecordId: cleanText(record.leftoverReviewRecordId),
      reviewStatus: cleanText(record.reviewStatus),
      reviewedAt: cleanText(record.reviewedAt),
      reviewedBy: cleanText(record.reviewedBy),
      reviewedByUserId: cleanText(record.reviewedByUserId),
      note: cleanText(record.note),
    }))
    .filter((record) => record.leftoverReturnRecordId && record.rollId);
}

export function normalizeRawMaterialLeftoverReviewRecords(records = []) {
  return (Array.isArray(records) ? records : [])
    .map((record) => ({
      ...record,
      leftoverReviewRecordId: cleanText(record.leftoverReviewRecordId ?? record.id),
      inboundId: cleanText(record.inboundId),
      leftoverReturnRecordId: cleanText(record.leftoverReturnRecordId),
      issueRecordId: cleanText(record.issueRecordId),
      rollId: cleanText(record.rollId),
      supplierRollNo: cleanText(record.supplierRollNo),
      materialType: cleanText(record.materialType),
      productName: cleanText(record.productName),
      spec: cleanText(record.spec),
      factoryColor: cleanText(record.factoryColor),
      returnedWeightKg: Number(record.returnedWeightKg) || 0,
      returnedQuantity: Number(record.returnedQuantity) || 0,
      reviewedWeightKg: Number(record.reviewedWeightKg) || 0,
      reviewedQuantity: Number(record.reviewedQuantity) || 0,
      unit: cleanText(record.unit),
      reviewLocation: cleanText(record.reviewLocation) || "原料库-余料可用区",
      reviewStatus: cleanText(record.reviewStatus) || "复核通过/可用",
      reviewedBy: cleanText(record.reviewedBy),
      reviewedByUserId: cleanText(record.reviewedByUserId),
      reviewedAt: cleanText(record.reviewedAt),
      note: cleanText(record.note),
    }))
    .filter((record) => record.leftoverReviewRecordId && record.rollId);
}

export function normalizeRawMaterialSplitRecords(records = []) {
  return (Array.isArray(records) ? records : [])
    .map((record) => ({
      ...record,
      splitRecordId: cleanText(record.splitRecordId ?? record.id),
      inboundId: cleanText(record.inboundId),
      sourceRollId: cleanText(record.sourceRollId),
      issuedRollId: cleanText(record.issuedRollId),
      supplierRollNo: cleanText(record.supplierRollNo),
      materialType: cleanText(record.materialType),
      productName: cleanText(record.productName),
      spec: cleanText(record.spec),
      factoryColor: cleanText(record.factoryColor),
      sourceWeightKg: Number(record.sourceWeightKg) || 0,
      issuedWeightKg: Number(record.issuedWeightKg) || 0,
      remainingWeightKg: Number(record.remainingWeightKg) || 0,
      unit: cleanText(record.unit),
      splitMode: cleanText(record.splitMode) || "部分领料/拆卷",
      machineId: cleanText(record.machineId),
      productionTaskId: cleanText(record.productionTaskId),
      productionTaskMatchStatus: cleanText(record.productionTaskMatchStatus),
      productionTaskMatchReason: cleanText(record.productionTaskMatchReason),
      productionTaskOrderLineId: cleanText(record.productionTaskOrderLineId),
      productionTaskMachineId: cleanText(record.productionTaskMachineId),
      productionTaskGoodsSpec: cleanText(record.productionTaskGoodsSpec),
      splitBy: cleanText(record.splitBy),
      splitByUserId: cleanText(record.splitByUserId),
      splitAt: cleanText(record.splitAt),
      note: cleanText(record.note),
    }))
    .filter((record) => record.splitRecordId && record.sourceRollId && record.issuedRollId);
}

function cleanText(value) {
  return String(value ?? "").trim();
}
