import { getUiActionState } from "../auth/seedPermissions.js";
import { isNavigationPageVisible, roleBoundaryPage } from "./navigation.js";

export function createOfficeWorkbenchRuntimes({
  attachmentActions,
  authState,
  currentUser,
  customers,
  driverDeliveryActions,
  findCustomer,
  firstReleaseMode,
  fulfillmentActions,
  getStatementBlockingAmount,
  interaction,
  inventoryActions,
  masterDataActions,
  officeWorkspace,
  orderActions,
  pageHelpers,
  permissionContext,
  printDeviceActions,
  productionPackingActions,
  rawMaterialActions,
  setActivePage,
  statementActions,
  todoActions,
  v1StatusActions,
}) {
  const pageRuntime = {
    ...officeWorkspace,
    authState,
    canOpenMasterData: isNavigationPageVisible("masterData", permissionContext),
    changePrinterDeviceQaCheck: printDeviceActions.changePrinterDeviceQaCheck,
    changePrinterDeviceQaEvidenceField: printDeviceActions.changePrinterDeviceQaEvidenceField,
    changePrinterDeviceQaField: printDeviceActions.changePrinterDeviceQaField,
    confirmRawMaterialSupplierPayment: rawMaterialActions.confirmRawMaterialSupplierPayment,
    confirmRawMaterialSupplierStatement: rawMaterialActions.confirmRawMaterialSupplierStatement,
    confirmRawMaterialSupplierStatementReviewDraft: rawMaterialActions.confirmRawMaterialSupplierStatementReviewDraft,
    currentUser,
    customers,
    dispatchPrintJobQueueItem: printDeviceActions.dispatchPrintJobQueueItem,
    enableMasterDataEmployeeAccounts: masterDataActions.enableMasterDataEmployeeAccounts,
    entryAction: orderActions.entryAction,
    firstReleaseMode,
    focusFulfillmentByRef: orderActions.focusFulfillmentByRef,
    focusInventoryLedgerSource: inventoryActions.focusInventoryLedgerSource,
    focusStatementByRef: orderActions.focusStatementByRef,
    generateRawMaterialSupplierPayableDraft: rawMaterialActions.generateRawMaterialSupplierPayableDraft,
    handleDraftCommand: orderActions.handleDraftCommand,
    handleDriverDeliveryAction: driverDeliveryActions.handleDriverDeliveryAction,
    handleInventoryCorrectionAttachment: inventoryActions.handleInventoryCorrectionAttachment,
    handleInventoryCorrectionConfirm: inventoryActions.handleInventoryCorrectionConfirm,
    handleInventoryCorrectionDraft: inventoryActions.handleInventoryCorrectionDraft,
    handleProductionPackingAction: productionPackingActions.handleProductionPackingAction,
    handleTodo: todoActions.handleTodo,
    linkCancellationIntentToSelectedLine: orderActions.linkCancellationIntentToSelectedLine,
    openInventoryCorrectionDetail: inventoryActions.openInventoryCorrectionDetail,
    openMasterDataTemplatePanel: masterDataActions.openMasterDataTemplatePanel,
    openOrderLineAction: orderActions.openOrderLineAction,
    openQueueDraft: orderActions.openQueueDraft,
    pageHelpers,
    permissionContext,
    recognize: orderActions.recognize,
    recognizeQueue: orderActions.recognizeQueue,
    recognizeRawMaterialDeliveryNote: rawMaterialActions.recognizeRawMaterialDeliveryNote,
    refreshDraftQueue: orderActions.refreshDraftQueue,
    refreshInventoryCorrectionQueueAction: inventoryActions.refreshInventoryCorrectionQueueAction,
    refreshInventoryLedgerAction: inventoryActions.refreshInventoryLedgerAction,
    refreshPrintDriverDiagnostics: productionPackingActions.refreshPrintDriverDiagnostics,
    refreshPrintJobs: productionPackingActions.refreshPrintJobs,
    repairTodoReference: todoActions.repairTodoReference,
    restoreCancelledDraftLine: orderActions.restoreCancelledDraftLine,
    retryPrintJobQueueItem: printDeviceActions.retryPrintJobQueueItem,
    roleBoundaryDescription: roleBoundaryPage.description,
    saveMasterDataMachine: masterDataActions.saveMasterDataMachine,
    saveMasterDataMaintenanceDraft: masterDataActions.saveMasterDataMaintenanceDraft,
    savePrinterDeviceMode: printDeviceActions.savePrinterDeviceMode,
    savePrinterDeviceQaRecord: printDeviceActions.savePrinterDeviceQaRecord,
    saveRawMaterialSupplierStatementReviewDraft: rawMaterialActions.saveRawMaterialSupplierStatementReviewDraft,
    selectPrinterDeviceQaDevice: printDeviceActions.selectPrinterDeviceQaDevice,
    setActivePage,
    setToast: interaction.setToast,
    statementAction: statementActions.statementAction,
    updateDraftField: orderActions.updateDraftField,
    updateFulfillment: fulfillmentActions.updateFulfillment,
    updateMasterDataEmployeeAssignment: masterDataActions.updateMasterDataEmployeeAssignment,
    updateMasterDataEmployeeProfile: masterDataActions.updateMasterDataEmployeeProfile,
    updateRawMaterialInbound: rawMaterialActions.updateRawMaterialInbound,
    uploadDraftArtwork: orderActions.uploadDraftArtwork,
    v1StatusActions,
  };

  const overlayRuntime = {
    attachmentViewer: interaction.attachmentViewer,
    closeAttachmentViewer: interaction.closeAttachmentViewer,
    closeMasterDataTemplatePanel: interaction.closeMasterDataTemplatePanel,
    closeModal: interaction.closeModal,
    closeOrderActionModal: interaction.closeOrderActionModal,
    confirmMasterDataEmployeeIdentity: masterDataActions.confirmMasterDataEmployeeIdentity,
    confirmModal: interaction.confirmModal,
    confirmOrderLineAction: interaction.confirmOrderLineAction,
    commitMasterDataImportExecutionFromPlan: masterDataActions.commitMasterDataImportExecutionFromPlan,
    createMasterDataFailedRowsCorrectionDraft: masterDataActions.createMasterDataFailedRowsCorrectionDraft,
    createMasterDataImportConfirmationPlanFromDraft: masterDataActions.createMasterDataImportConfirmationPlanFromDraft,
    createMasterDataImportExecutionFromPlan: masterDataActions.createMasterDataImportExecutionFromPlan,
    createMasterDataImportReviewDraftFromPrecheck: masterDataActions.createMasterDataImportReviewDraftFromPrecheck,
    downloadMasterDataImportFailedRows: masterDataActions.downloadMasterDataImportFailedRows,
    downloadMasterDataTemplate: masterDataActions.downloadMasterDataTemplate,
    downloadViewedAttachment: attachmentActions.downloadViewedAttachment,
    employeeAccountReviews: officeWorkspace.masterDataEmployeeAccountReviews,
    enableMasterDataEmployeeAccount: masterDataActions.enableMasterDataEmployeeAccount,
    findCustomer,
    fulfillments: officeWorkspace.fulfillments,
    getStatementBlockingAmount,
    getUiActionState: (surface, action) => getUiActionState(permissionContext, surface, action),
    importExecutions: officeWorkspace.masterDataImportExecutions,
    issueMasterDataEmployeeAccountPassword: masterDataActions.issueMasterDataEmployeeAccountPassword,
    lastIssuedEmployeeCredential: officeWorkspace.lastIssuedEmployeeCredential,
    masterDataConfirmationPlans: officeWorkspace.masterDataImportConfirmationPlans,
    masterDataPrecheckState: officeWorkspace.masterDataPrecheckState,
    masterDataReviewDrafts: officeWorkspace.masterDataImportReviewDrafts,
    masterDataTemplatePanel: interaction.masterDataTemplatePanel,
    modal: interaction.modal,
    onPrecheckMasterDataTemplate: masterDataActions.precheckMasterDataTemplate,
    onRefreshEmployeeAccountReviews: (options) => (
      officeWorkspace.refreshMasterDataEmployeeAccountReviews(options).then((result) => {
        if (result?.feedback) interaction.setToast(result.feedback);
        return result;
      })
    ),
    orderActionModal: interaction.orderActionModal,
    orderLines: officeWorkspace.orderLines,
    revokeMasterDataEmployeeAccountPassword: masterDataActions.revokeMasterDataEmployeeAccountPassword,
    statements: officeWorkspace.statements,
  };

  return { overlayRuntime, pageRuntime };
}
