import { useInboundPageState } from "./useInboundPageState.js";
import { InboundDetail } from "./InboundDetail.jsx";
import { RawMaterialMobileReceiving } from "./RawMaterialMobileReceiving.jsx";
import { RawMaterialLabelPrintSheet } from "./RawMaterialLabelPrintSheet.jsx";
import { RawMaterialInboundListPane, RawMaterialRollInventoryWorkbench } from "./RawMaterialInboundWorkbench.jsx";

export function RawMaterialInboundPage(props) {
  const {
    activeTab,
    attachState,
    authState,
    canViewCost,
    changeTab,
    consumptionState,
    costConfirmState,
    costDraftState,
    currentUser,
    deliveryNoteCapturePages,
    deliveryNoteOcrError,
    deliveryNoteOcrLoading,
    deliveryNoteOcrProgress,
    deliveryNoteOcrResult,
    deliveryNotePreviewByInboundId,
    desktopView,
    detailTab,
    exceptionState,
    firstReleaseMode,
    handleConfirmSupplierPayment,
    handleConfirmSupplierStatement,
    handleConfirmSupplierStatementReview,
    handleDeliveryNotePageRemove,
    handleDeliveryNotePageSelect,
    handleDeliveryNotePagesClear,
    handleDeliveryNoteRecognize,
    handleDesktopDeliveryNoteRecognize,
    handleGenerateSupplierPayableDraft,
    handleMobileAttach,
    handleMobileStageChange,
    handleOcrReviewConfirm,
    handleOpenRollSource,
    handlePrintLabels,
    handleReprintLabel,
    handleSaveSupplierStatementReviewDraft,
    handleSelectInbound,
    handleSupplierStatementImport,
    inbounds,
    issueSelection,
    issueState,
    keyword,
    labelVerification,
    leftoverReviewState,
    leftoverState,
    lossCalibrationState,
    marginReviewState,
    marginSnapshotState,
    meta,
    metrics,
    mobileMessage,
    mobileOcrReviewActive,
    mobileOcrReviewOpen,
    mobileSelected,
    mobileStage,
    money,
    ocrLineReviewDraft,
    ocrReviewDraft,
    ocrReviewSubmitError,
    ocrReviewSubmitting,
    onAction,
    payableState,
    paymentState,
    printSheetInbound,
    printState,
    printerDeviceQa,
    productionTasks,
    records,
    reviewState,
    selected,
    selectedOrderSupport,
    selectedStock,
    selectedTaskCandidate,
    setDesktopView,
    setDetailTab,
    setIssueSelection,
    setKeyword,
    setLabelVerification,
    setOcrLineReviewDraft,
    setOcrReviewDraft,
    statementImport,
    statementImportLoading,
    statementReviewMeta,
    statementReviewSaving,
    statementReviews,
    visibleRecords
  } = useInboundPageState(props);
  return (
    <section className={`page-grid split-detail operational-split-workbench raw-material-inbound-page raw-material-workbench ${desktopView === "卷料库存" ? "is-roll-inventory-view" : "is-receiving-view"} ${mobileOcrReviewOpen ? "is-mobile-detail-open" : ""}`}>
      <RawMaterialLabelPrintSheet inbound={printSheetInbound} />
      <RawMaterialMobileReceiving
        attachState={attachState}
        deliveryNoteOcrError={deliveryNoteOcrError}
        deliveryNoteOcrLoading={deliveryNoteOcrLoading}
        deliveryNoteOcrProgress={deliveryNoteOcrProgress}
        deliveryNoteOcrResult={deliveryNoteOcrResult}
        capturedPages={deliveryNoteCapturePages}
        mobileMessage={mobileMessage}
        mobileStage={mobileStage}
        onAttach={handleMobileAttach}
        onDeliveryNotePageSelect={handleDeliveryNotePageSelect}
        onDeliveryNotePageRemove={handleDeliveryNotePageRemove}
        onDeliveryNotePagesClear={handleDeliveryNotePagesClear}
        onDeliveryNoteRecognize={() => handleDeliveryNoteRecognize()}
        onPrint={handlePrintLabels}
        onStageChange={handleMobileStageChange}
        printState={printState}
        printerDeviceQa={printerDeviceQa}
        records={inbounds}
        reviewState={reviewState}
        selected={mobileSelected}
      />
      <RawMaterialRollInventoryWorkbench
        inbounds={inbounds}
        meta={meta}
        onOpenReceiving={() => setDesktopView("收货录入")}
        onOpenSource={handleOpenRollSource}
      />
      <RawMaterialInboundListPane
        activeTab={activeTab}
        inbounds={inbounds}
        keyword={keyword}
        meta={meta}
        metrics={metrics}
        onKeywordChange={setKeyword}
        onSelect={handleSelectInbound}
        onTabChange={changeTab}
        records={records}
        selectedId={selected?.id}
        visibleRecords={visibleRecords}
        firstReleaseMode={firstReleaseMode}
        onOpenInventory={() => setDesktopView("卷料库存")}
      />
      <InboundDetail {...{
        attachState,
        authState,
        canViewCost,
        consumptionState,
        costConfirmState,
        costDraftState,
        currentUser,
        deliveryNoteOcrError,
        deliveryNoteOcrLoading,
        deliveryNoteOcrResult,
        deliveryNotePreviewByInboundId,
        detailTab,
        exceptionState,
        firstReleaseMode,
        handleConfirmSupplierPayment,
        handleConfirmSupplierStatement,
        handleConfirmSupplierStatementReview,
        handleDesktopDeliveryNoteRecognize,
        handleGenerateSupplierPayableDraft,
        handleMobileStageChange,
        handleOcrReviewConfirm,
        handlePrintLabels,
        handleReprintLabel,
        handleSaveSupplierStatementReviewDraft,
        handleSupplierStatementImport,
        issueSelection,
        issueState,
        labelVerification,
        leftoverReviewState,
        leftoverState,
        lossCalibrationState,
        marginReviewState,
        marginSnapshotState,
        meta,
        mobileOcrReviewActive,
        money,
        ocrLineReviewDraft,
        ocrReviewDraft,
        ocrReviewSubmitError,
        ocrReviewSubmitting,
        onAction,
        payableState,
        paymentState,
        printState,
        productionTasks,
        reviewState,
        selected,
        selectedOrderSupport,
        selectedStock,
        selectedTaskCandidate,
        setDetailTab,
        setIssueSelection,
        setLabelVerification,
        setOcrLineReviewDraft,
        setOcrReviewDraft,
        statementImport,
        statementImportLoading,
        statementReviewMeta,
        statementReviewSaving,
        statementReviews
      }} />
    </section>
  );
}
