export const orderConversationCorpusVersion = "order-conversation-corpus-v1";

export const orderConversationCorpus = Object.freeze([
  Object.freeze({
    id: "stock-group-multi-block-001",
    label: "单客户多时段现货订单、询库存与缺货取消",
    sourceKind: "confirmed_anonymized_business_case",
    confirmedAt: "2026-07-12",
    options: {
      currentDraftStatus: "待审核",
      now: "2026-07-12T08:00:00.000Z",
    },
    messages: [
      {
        id: "CORPUS-001-AM-ORDER",
        conversationId: "ANON-GROUP-001",
        customerId: "C001",
        sender: "客户甲",
        senderRole: "customer",
        sentAt: "2026-07-12 09:02",
        text: "覆膜袋 40*30 橘色100 宝蓝200",
      },
      {
        id: "CORPUS-001-INQUIRY",
        conversationId: "ANON-GROUP-001",
        customerId: "C001",
        sender: "客户甲",
        senderRole: "customer",
        sentAt: "2026-07-12 10:11",
        text: "35*27 焦糖米提100个有吗？",
      },
      {
        id: "CORPUS-001-OFFICE-REPLY",
        conversationId: "ANON-GROUP-001",
        sender: "办公室甲",
        senderRole: "office",
        sentAt: "2026-07-12 10:12",
        text: "有",
      },
      {
        id: "CORPUS-001-CUSTOMER-CONFIRM",
        conversationId: "ANON-GROUP-001",
        customerId: "C001",
        sender: "客户甲",
        senderRole: "customer",
        sentAt: "2026-07-12 10:14",
        text: "要",
      },
      {
        id: "CORPUS-001-PM-ORDER",
        conversationId: "ANON-GROUP-001",
        customerId: "C001",
        sender: "客户甲",
        senderRole: "customer",
        sentAt: "2026-07-12 15:03",
        text: "40+30 米白咖提300个",
      },
      {
        id: "CORPUS-001-PM-ADD",
        conversationId: "ANON-GROUP-001",
        customerId: "C001",
        sender: "客户甲",
        senderRole: "customer",
        sentAt: "2026-07-12 15:04",
        text: "再加 40*30 安哥拉红安哥拉红提手100个",
      },
      {
        id: "CORPUS-001-HOLD",
        conversationId: "ANON-GROUP-001",
        customerId: "C001",
        sender: "客户甲",
        senderRole: "customer",
        sentAt: "2026-07-12 16:20",
        text: "35*27白色有的话给我留50个",
      },
      {
        id: "CORPUS-001-DUPLICATE",
        conversationId: "ANON-GROUP-001",
        customerId: "C001",
        sender: "客户甲",
        senderRole: "customer",
        sentAt: "2026-07-12 16:21",
        text: "40+30 米白咖提300个",
      },
      {
        id: "CORPUS-001-SHORTAGE-CANCEL",
        conversationId: "ANON-GROUP-001",
        customerId: "C001",
        sender: "客户甲",
        senderRole: "customer",
        sentAt: "2026-07-12 16:30",
        text: "没货的那两款不要了，其他继续",
      },
    ],
    expected: {
      summary: {
        messageCount: 9,
        originalOrderCount: 2,
        orderRowCount: 4,
        inventoryInquiryCount: 1,
        temporaryHoldCount: 1,
        duplicateCandidateCount: 1,
        shortageCancellationCount: 1,
        cancelledDraftLineCount: 2,
      },
      messageIntents: {
        "CORPUS-001-AM-ORDER": "explicit_order",
        "CORPUS-001-INQUIRY": "inventory_inquiry",
        "CORPUS-001-OFFICE-REPLY": "merchant_reply",
        "CORPUS-001-CUSTOMER-CONFIRM": "inventory_confirmation",
        "CORPUS-001-PM-ORDER": "explicit_order",
        "CORPUS-001-PM-ADD": "follow_up",
        "CORPUS-001-HOLD": "temporary_hold",
        "CORPUS-001-DUPLICATE": "duplicate_candidate",
        "CORPUS-001-SHORTAGE-CANCEL": "shortage_cancellation",
      },
      rows: [
        { sourceMessageId: "CORPUS-001-AM-ORDER", size: "40*30*10", color: "橘色", qty: 100, style: "覆膜袋", print: "否" },
        { sourceMessageId: "CORPUS-001-AM-ORDER", size: "40*30*10", color: "宝蓝色", qty: 200, style: "覆膜袋", print: "否" },
        { sourceMessageId: "CORPUS-001-PM-ORDER", size: "40*30*10", color: "米白色", handleColor: "咖色", qty: 300, requiresDimensionConfirmation: true },
        { sourceMessageId: "CORPUS-001-PM-ADD", size: "40*30*10", color: "安哥拉红", handleColor: "安哥拉红", qty: 100, appendDecision: "append_to_unconfirmed_draft" },
      ],
      holdExpiresAt: "2026-07-12T19:30:00+08:00",
      duplicateOf: "CORPUS-001-PM-ORDER",
    },
  }),
]);
