import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

export const migrationDir = path.resolve("db/migrations");

export const requiredTables = [
  "roles",
  "users",
  "user_roles",
  "permissions",
  "role_permissions",
  "user_permission_grants",
  "seed_session_revocations",
  "customers",
  "customer_contacts",
  "customer_addresses",
  "customer_notes",
  "standard_colors",
  "color_aliases",
  "size_specs",
  "finished_goods_styles",
  "price_tables",
  "price_table_items",
  "employees",
  "machines",
  "employee_machine_assignments",
  "machine_capacity_baselines",
  "master_data_import_review_drafts",
  "master_data_import_confirmation_plans",
  "master_data_import_executions",
  "raw_material_supplier_statement_reviews",
  "production_schedule_records",
  "order_drafts",
  "order_draft_lines",
  "original_orders",
  "order_lines",
  "order_line_change_records",
  "price_snapshots",
  "inventory_items",
  "inventory_reservations",
  "inventory_ledger_entries",
  "inventory_correction_drafts",
  "production_tasks",
  "workshop_reports",
  "packing_tasks",
  "packages",
  "fulfillment_records",
  "driver_delivery_dispatches",
  "driver_device_field_tests",
  "fulfillment_exceptions",
  "print_templates",
  "printer_devices",
  "print_records",
  "print_jobs",
  "print_batch_records",
  "statements",
  "statement_lines",
  "statement_export_files",
  "statement_send_records",
  "statement_confirmation_records",
  "payment_records",
  "variance_records",
  "todos",
  "todo_events",
  "attachments",
  "attachment_links",
  "attachment_content_dedup_keys",
  "attachment_access_logs",
  "operation_logs",
  "operation_idempotency_keys",
  "after_sales_records",
  "responsibility_clues",
];

export const requiredTableColumns = {
  production_tasks: [
    "id",
    "order_line_id",
    "task_status",
    "revision",
    "finished_goods_photo",
    "created_by",
    "created_at",
    "updated_at",
  ],
  inventory_correction_drafts: [
    "id",
    "inventory_item_id",
    "expected_qty",
    "actual_qty",
    "delta_qty",
    "reason",
    "status",
    "revision",
    "todo_id",
    "remark",
    "attachment_ids",
    "created_by",
    "confirmed_by",
    "confirmed_at",
    "created_at",
    "updated_at",
  ],
  operation_idempotency_keys: [
    "scope",
    "idempotency_key",
    "request_hash",
    "response_json",
    "operator_id",
    "target_type",
    "target_id",
    "created_at",
    "completed_at",
    "expires_at",
  ],
  users: [
    "id",
    "login_name",
    "display_name",
    "default_role_id",
    "department",
    "enabled",
    "source",
    "employee_id",
    "default_machine_id",
    "login_enabled",
    "password_hash",
    "password_status",
    "must_change_password",
    "password_issued_by",
    "password_issued_at",
    "password_changed_by",
    "password_changed_at",
    "password_revoked_by",
    "password_revoked_at",
    "session_valid_after",
    "session_version",
    "metadata_json",
    "updated_at",
  ],
  seed_session_revocations: ["jti", "user_id", "revoked_at", "expires_at", "reason", "source", "created_at"],
  attachments: [
    "id",
    "file_name",
    "file_type",
    "purpose",
    "mime_type",
    "file_size_bytes",
    "has_content",
    "storage_provider",
    "storage_key",
    "storage_url",
    "content_ref",
    "content_digest",
    "thumbnail_storage_key",
    "thumbnail_url",
    "signed_url_expires_at",
    "uploaded_by",
    "uploaded_at",
    "status",
    "updated_at",
  ],
  attachment_links: ["id", "attachment_id", "owner_type", "owner_id", "purpose", "created_at"],
  attachment_content_dedup_keys: [
    "owner_type",
    "owner_id",
    "purpose",
    "content_digest",
    "attachment_id",
    "created_at",
  ],
  attachment_access_logs: [
    "id",
    "attachment_id",
    "operation_log_id",
    "action",
    "operator_id",
    "access_mode",
    "delivery_mode",
    "storage_provider",
    "storage_key",
    "owner_type",
    "owner_id",
    "purpose",
    "file_name",
    "content_type",
    "expires_at",
    "metadata_json",
    "occurred_at",
    "created_at",
  ],
  statement_export_files: [
    "id",
    "statement_id",
    "preview_type",
    "download_token",
    "file_name",
    "content_type",
    "storage_provider",
    "storage_key",
    "content_text",
    "content_digest",
    "operation_log_id",
    "created_by",
    "created_at",
    "metadata_json",
  ],
  statement_lines: [
    "id",
    "statement_id",
    "order_line_id",
    "fulfillment_id",
    "delivered_qty",
    "chargeable_qty",
    "free_qty",
    "amount",
    "adjustment_amount",
    "final_amount",
    "created_at",
  ],
  statement_confirmation_records: [
    "id",
    "statement_id",
    "send_record_id",
    "confirmation_type",
    "channel",
    "confirmed_by_customer",
    "confirmed_at",
    "content",
    "attachment_ids_json",
    "recorded_by",
    "operation_log_id",
    "created_at",
  ],
  print_batch_records: [
    "id",
    "biz_no",
    "action",
    "result_label",
    "status",
    "todo_ids",
    "todo_refs",
    "total_task_count",
    "total_label_count",
    "printed_label_count",
    "pending_label_count",
    "printed_package_ids",
    "pending_package_ids",
    "print_packages_json",
    "printed_packages_json",
    "pending_packages_json",
    "summary",
    "operation_log_id",
    "operator_id",
    "operator_name",
    "created_at",
    "metadata_json",
  ],
  employees: [
    "id",
    "biz_no",
    "user_id",
    "name",
    "role_name",
    "default_workshop",
    "default_machine_id",
    "base_hourly_wage",
    "position_allowance_hourly",
    "wage_effective_from",
    "account_enabled",
    "profile_status",
    "requested_enabled",
    "remark",
    "created_by",
    "created_at",
    "updated_at",
  ],
  machines: [
    "id",
    "biz_no",
    "name",
    "machine_type",
    "workshop",
    "status",
    "enabled",
    "settings_json",
    "created_by",
    "created_at",
    "updated_at",
  ],
  employee_machine_assignments: [
    "id",
    "employee_id",
    "machine_id",
    "assignment_type",
    "workshop",
    "effective_from",
    "effective_to",
    "enabled",
    "created_by",
    "created_at",
    "updated_at",
  ],
  machine_capacity_baselines: [
    "id",
    "machine_id",
    "size_key",
    "daily_capacity_qty",
    "hourly_capacity_qty",
    "source_kind",
    "confidence",
    "effective_from",
    "remark",
    "created_by",
    "created_at",
    "updated_at",
  ],
  master_data_import_review_drafts: [
    "id",
    "status",
    "file_name",
    "requested_by",
    "checked_at",
    "payload_json",
    "created_at",
    "updated_at",
  ],
  master_data_import_confirmation_plans: [
    "id",
    "draft_id",
    "status",
    "file_name",
    "created_by",
    "operation_log_id",
    "last_execution_id",
    "last_execution_status",
    "last_execution_at",
    "payload_json",
    "created_at",
    "updated_at",
  ],
  master_data_import_executions: [
    "id",
    "plan_id",
    "draft_id",
    "status",
    "file_name",
    "requested_by",
    "requested_at",
    "official_writer_kind",
    "operation_log_id",
    "payload_json",
    "created_at",
    "updated_at",
  ],
  raw_material_supplier_statement_reviews: [
    "id",
    "supplier_name",
    "file_name",
    "status",
    "review_status",
    "payload_json",
    "created_at",
    "updated_at",
  ],
  production_schedule_records: [
    "id",
    "biz_no",
    "production_task_id",
    "order_line_id",
    "published_schedule_id",
    "machine_id",
    "queue_seq",
    "schedule_status",
    "source_kind",
    "planned_start_at",
    "planned_end_at",
    "sequence_updated_at",
    "sequence_updated_by",
    "remark",
    "created_by",
    "created_at",
    "updated_at",
  ],
  original_orders: [
    "id",
    "biz_no",
    "source_draft_id",
    "customer_id",
    "customer_snapshot",
    "source_text",
    "summary_status",
    "created_by",
    "created_at",
    "updated_at",
  ],
  order_lines: [
    "id",
    "biz_no",
    "order_id",
    "customer_id",
    "product_name",
    "order_type",
    "size",
    "bag_color",
    "handle_type",
    "style",
    "print_flag",
    "print_color",
    "print_side",
    "handle_color",
    "original_qty",
    "fulfillment_method",
    "line_status",
    "exception_tags",
    "created_by",
    "created_at",
    "updated_at",
  ],
  price_snapshots: [
    "id",
    "order_line_id",
    "snapshot_type",
    "version_no",
    "bag_price",
    "print_price",
    "other_fee",
    "adjustment_amount",
    "chargeable_qty",
    "final_amount",
    "created_by",
    "created_at",
  ],
  fulfillment_records: [
    "id",
    "biz_no",
    "order_line_id",
    "customer_id",
    "customer_snapshot",
    "method",
    "expected_qty",
    "actual_qty",
    "status",
    "watermarked_photo_attached",
    "watermarked_photo_attachment_id",
    "watermark_id",
    "loaded_at",
    "loaded_by",
    "driver_remark",
    "receiver_name",
    "paper_note_status",
    "signature_photo_attachment_id",
    "delivery_evidence_review_status",
    "delivery_evidence_reviewed_at",
    "delivery_evidence_reviewed_by_user_id",
    "delivery_evidence_issue_reason",
    "created_by",
    "created_at",
    "updated_at",
    "revision",
  ],
  driver_delivery_dispatches: [
    "id",
    "biz_no",
    "fulfillment_id",
    "driver_id",
    "route_date",
    "route_batch_no",
    "stop_sequence",
    "dispatch_status",
    "planned_departure_at",
    "assigned_by",
    "assigned_at",
    "remark",
    "created_at",
    "updated_at",
    "revision",
  ],
  inventory_items: ["id", "inventory_key", "on_hand_qty", "reserved_qty", "updated_at", "revision"],
  statements: ["id", "customer_id", "receivable_amount", "received_amount", "variance_amount", "updated_at", "revision"],
  raw_material_inbounds: ["id", "status", "payload_json", "updated_at", "revision"],
  driver_device_field_tests: [
    "id",
    "biz_no",
    "fulfillment_id",
    "order_line_id",
    "driver_id",
    "operator_id",
    "operator_name",
    "checked_at",
    "device_label",
    "browser_label",
    "user_agent",
    "language",
    "checks_json",
    "summary_json",
    "note",
    "operation_log_id",
    "created_at",
    "updated_at",
  ],
  inventory_reservations: [
    "id",
    "order_line_id",
    "inventory_item_id",
    "reserved_qty",
    "reservation_type",
    "status",
    "expires_at",
    "created_by",
    "created_at",
    "updated_at",
  ],
  inventory_ledger_entries: [
    "id",
    "inventory_item_id",
    "change_type",
    "qty_before",
    "qty_change",
    "qty_after",
    "source_type",
    "source_id",
    "operator_id",
    "confirmed_by",
    "occurred_at",
    "created_at",
    "reason",
    "remark",
  ],
  print_templates: [
    "id",
    "template_key",
    "template_type",
    "name",
    "status",
    "template_payload",
    "created_by",
    "created_at",
    "updated_at",
  ],
  print_records: [
    "id",
    "biz_no",
    "target_type",
    "target_id",
    "template_id",
    "printer_device_id",
    "printer_device_snapshot",
    "batch_no",
    "print_action",
    "status",
    "printed_by",
    "printed_at",
    "created_at",
  ],
  print_jobs: [
    "id",
    "biz_no",
    "print_record_id",
    "target_type",
    "target_id",
    "document_type",
    "template_id",
    "printer_device_id",
    "printer_device_snapshot",
    "driver_mode",
    "job_status",
    "attempt_no",
    "source_print_job_id",
    "requested_by",
    "queued_at",
    "sent_at",
    "finished_at",
    "error_code",
    "error_message",
    "payload_json",
    "metadata_json",
    "operation_log_id",
    "created_at",
    "updated_at",
    "revision",
  ],
  printer_devices: [
    "id",
    "biz_no",
    "name",
    "device_type",
    "status",
    "connection_type",
    "connection_uri",
    "driver_name",
    "supported_document_types",
    "default_document_types",
    "paper_width_mm",
    "paper_height_mm",
    "paper_name",
    "is_continuous",
    "dpi",
    "default_copies",
    "darkness",
    "speed",
    "cutter_enabled",
    "settings_json",
    "created_by",
    "updated_by",
    "created_at",
    "updated_at",
    "revision",
  ],
  fulfillment_exceptions: [
    "id",
    "fulfillment_id",
    "exception_type",
    "expected_qty",
    "actual_qty",
    "reason_code",
    "reason",
    "status",
    "todo_id",
    "reported_by",
    "occurred_at",
    "created_at",
    "updated_at",
  ],
  todos: [
    "id",
    "biz_no",
    "type",
    "ref_type",
    "ref_id",
    "priority",
    "status",
    "summary",
    "due_at",
    "remind_at",
    "handled_by",
    "handled_at",
    "handling_result",
    "created_by",
    "created_at",
    "updated_at",
  ],
};

export function loadMigrationFiles() {
  if (!fs.existsSync(migrationDir)) {
    throw new Error(`Migration directory not found: ${migrationDir}`);
  }

  return fs
    .readdirSync(migrationDir)
    .filter((file) => file.endsWith(".sql"))
    .sort()
    .map((filename) => {
      const filePath = path.join(migrationDir, filename);
      const sql = fs.readFileSync(filePath, "utf8");
      return {
        filename,
        id: filename.replace(/\.sql$/, ""),
        path: filePath,
        sql,
        checksum: crypto.createHash("sha256").update(sql).digest("hex"),
      };
    });
}

export function validateMigrationSet(migrations) {
  if (migrations.length < 4) {
    throw new Error(`Expected at least 4 migration files, found ${migrations.length}`);
  }

  migrations.forEach((migration, index) => {
    const expectedPrefix = String(index + 1).padStart(4, "0");
    if (!migration.filename.startsWith(`${expectedPrefix}_`)) {
      throw new Error(`Migration order gap: expected ${expectedPrefix}_*, got ${migration.filename}`);
    }
  });

  const createdTables = new Set();
  const createdTableColumns = new Map();
  for (const migration of migrations) {
    if (/\bdrop\s+table\b/i.test(migration.sql)) {
      throw new Error(`${migration.filename} contains DROP TABLE; first-core migrations should be additive drafts`);
    }
    for (const match of migration.sql.matchAll(/create\s+table\s+if\s+not\s+exists\s+([a-z_][a-z0-9_]*)/gi)) {
      createdTables.add(match[1]);
    }
    for (const tableName of Object.keys(requiredTableColumns)) {
      const columns = [
        ...extractCreateTableColumns(migration.sql, tableName),
        ...extractAlterTableAddedColumns(migration.sql, tableName),
      ];
      if (columns.length > 0) {
        const existing = createdTableColumns.get(tableName) ?? new Set();
        for (const column of columns) existing.add(column);
        createdTableColumns.set(tableName, existing);
      }
    }
  }

  const missingTables = requiredTables.filter((table) => !createdTables.has(table));
  if (missingTables.length > 0) {
    throw new Error(`Missing required migration tables: ${missingTables.join(", ")}`);
  }

  for (const [tableName, requiredColumns] of Object.entries(requiredTableColumns)) {
    const columns = createdTableColumns.get(tableName) ?? new Set();
    const missingColumns = requiredColumns.filter((column) => !columns.has(column));
    if (missingColumns.length > 0) {
      throw new Error(`Missing required columns on ${tableName}: ${missingColumns.join(", ")}`);
    }
  }

  return { createdTables };
}

function extractCreateTableColumns(sql, tableName) {
  const pattern = new RegExp(`create\\s+table\\s+if\\s+not\\s+exists\\s+${tableName}\\s*\\(([^]*?)\\);`, "i");
  const match = sql.match(pattern);
  if (!match) return [];
  return match[1]
    .split(/\n/)
    .map((line) => line.trim().replace(/,$/, ""))
    .filter(Boolean)
    .map((line) => line.match(/^([a-z_][a-z0-9_]*)\b/i)?.[1])
    .filter(Boolean)
    .filter((column) => !["constraint", "primary", "unique", "foreign", "check"].includes(column.toLowerCase()))
    .map((column) => column.toLowerCase());
}

function extractAlterTableAddedColumns(sql, tableName) {
  const pattern = new RegExp(
    `alter\\s+table\\s+${tableName}\\s+add\\s+column\\s+(?:if\\s+not\\s+exists\\s+)?([a-z_][a-z0-9_]*)\\b`,
    "gi",
  );
  return Array.from(sql.matchAll(pattern), (match) => match[1].toLowerCase());
}
